'use client'

import { createContext, useContext, useState, useEffect } from 'react'

interface LanguageContextType {
  lang: string
  setLang: (lang: string) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionaries
const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    projects: 'Projects',
    team: 'Team',
    analytics: 'Analytics',
    settings: 'Settings',
    logout: 'Logout',
    welcome: 'Welcome',
    'dashboard subtitle': 'Welcome to your dashboard',
    'analytics dashboard': 'Analytics Dashboard',
    'analytics dashboard subtitle': 'View insights and performance metrics',
    'monthly comparison': 'Monthly Comparison',
    'analytics loading': 'Loading analytics...',
    'analytics load error': 'Failed to load analytics',
    'analytics error': 'An error occurred while loading analytics',
    'analytics no data': 'No analytics data available',
    'comparison chart title': 'Monthly Comparison',
    'this month': 'This Month',
    'last month': 'Last Month',
    'user reports': 'User Reports',
    'user reports subtitle': 'User Reports Subtitle',
    'generate monthly report': 'Generate Monthly Report',
    'month': 'Month',
    'year': 'Year',
    'download pdf report': 'Download PDF Report',
    'my projects': 'My Projects',
    'my tasks': 'My Tasks',
    'teams joined': 'Teams Joined',
    'active teams': 'Active Teams',
    'contribution score': 'Contribution Score',
    'generating': 'Generating...',
    'admin analytics title': 'Admin Analytics Title',
    'admin analytics subtitle': 'Admin Analytics Subtitle',
    'real time label': 'Real Time Label',
    'total users': 'Total Users',
    'active users': 'Active Users',
    'completed projects': 'Completed Projects',
    'across all projects': 'Across All Projects',
    'total admins': 'Total Admins',
    'system admins': 'System Admins',
    'user registration trend': 'User Registration Trend',
    'user registration trend desc': 'User Registration Trend Desc',
    'project status distribution title': 'Project Status Distribution Title',
    'project status distribution desc': 'Project Status Distribution Desc',
    'user activity overview': 'User Activity Overview',
    'active users vs new registrations over time': 'Active Users vs New Registrations Over Time',
    'yearly registration growth': 'Yearly Registration Growth',
    'yearly registration growth desc': 'Yearly Registration Growth Desc',
    'last year': 'Last Year',
    'completed tasks': 'Completed Tasks',
    'completion rate title': 'Task Completion Rate',
    'trend chart title': 'Monthly Trend',
    'team growth title': 'Team Growth',

    // Team
    team_subtitle: 'Manage your team members',
    add_member: 'Add Member',
    team_search_placeholder: 'Search team members...',
    refresh: 'Refresh',
    detail: 'Detail',
    team_empty: 'No team members found',

    // Common
    back: 'Back',
    cancel: 'Cancel',
    createTask: 'Create Task',
    edit: 'Edit',
    delete: 'Delete',
    remove: 'Remove',
    save: 'Save',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    'total projects': 'Total Projects',
    'total tasks': 'Total Tasks',
    'total members': 'Total Members',
    'avg progress': 'Average Progress',
    'undo': 'Undo',
    'redo': 'Redo',

    // Quick Actions
    qaNewProject: 'Start New Project',
    qaAddTask: 'Add New Task',
    qaInviteMember: 'Invite Member',

    // Task related
    tasks: 'Tasks',
    taskTitle: 'Task Title',
    taskDescription: 'Task Description',
    taskPriority: 'Priority',
    status: 'Status',
    pending: 'Pending',
    in_progress: 'In Progress',
    review: 'Review',
    completed: 'Completed',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    urgent: 'Urgent',
    endDate: 'Due Date',
    assignTo: 'Assign To',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    membersSelected: 'Members Selected',
    selectProjectFirst: 'Select A Project First',
    createNewTask: 'Create New Task',
    createNewTaskSubtitle: 'Add A New Task To Your Project',
    enterTaskTitle: 'Enter Task Title',
    describeThisTask: 'Describe This Task',
    selectProject: 'Select Project',
    description: 'Description',

    // Team related
    'add team member title': 'Add Team Member',
    'add team member subtitle': 'Add A New Member To Your Team',
    'search user label': 'Search User',
    'enter username or email placeholder': 'Enter Username Or Email',
    'search button': 'Search',
    searchingStatus: 'Searching...',
    'select team project': 'Select Team Project',
    'choose team project': 'Choose Team Project',
    'role label': 'Role',
    'member role': 'Member',
    adminRole: 'Admin',
    founderRole: 'Founder',
    'add team member button': 'Add Team Member',
    'add task': 'Add Task',
    'project history': 'Project History',
    'no changes yet': 'No Changes Yet',
    completeDataWarning: 'Complete Data Warning',
    pleaseCompleteAllFieldsMessage: 'Please Complete All Required Fields',
    successStatus: 'Success',
    memberAddedSuccessfullyMessage: 'Member Added Successfully',
    'member removed successfully': 'Member Removed Successfully',
    failedStatus: 'Failed',
    failedAddMemberError: 'Failed To Add Member',
    errorOccurredMessage: 'An Error Occurred',
    selectUserLabel: 'Select User',
    memberDetails: 'Member Details',
    editRole: 'Edit Role',
    online: 'Online',
    monthlyData: 'Joined',
    lastActive: 'Last Active',
    projectMemberships: 'Project Memberships',
    thisMemberNotInAnyProject: 'This Member Is Not In Any Project',
    viewProject: 'View Project',
    memberNotFound: 'Member Not Found',
    memberNotFoundDesc: 'The Requested Member Could Not Be Found',
    noName: 'No Name',
    member: 'Member',
    'confirm remove member': 'Confirm Remove Member ?',
    'are you sure remove member': 'Are you sure remove member ?',
    'this action cannot be undone': 'this action cannot be undone ?',
    'confirm delete task': 'Confirm Delete Task ?',
    'are you sure delete task': 'Are you sure delete task',
    'edit role for': 'Edit Role for',
    'select new role': 'Select New Role',
    'update role': 'Update Role',
    project_created_successfully: 'Project created successfully',
    member_details: 'Member Details',
    project_memberships: 'Project Memberships',
    monthly_data: 'monthly data',
    view_project: 'View Project',
    last_active: 'last active',
    edit_member_role: 'Edit Member Role',
    edit_member_role_subtitle: 'Edit member role subtitle',
    member_information: 'Member Information',
    roles_in_projects: 'Roles In Projects',

    // Project related
    planning: 'Planning',
    on_hold: 'On Hold',
    'latest projects': 'Proyek Terbaru',
    'view all': 'Lihat Semua',
    'projects subtitle': 'Kelola semua proyek Anda',
    'new project': 'Proyek Baru',
    'members label': 'anggota',
    'tasks label': 'Tugas',
    'view details': 'Lihat Detail',
    'edit project': 'Edit Proyek',
    'create new project': 'Buat Proyek Baru',
    'create new project subtitle': 'Buat proyek baru untuk memulai',
    'project name': 'Nama Proyek',
    'enter project name': 'Masukkan nama proyek',
    'describe this project': 'Jelaskan proyek ini',
    'you can edit later': 'Anda dapat mengedit ini nanti',
    'project status': 'Status Proyek',
    'end date': 'Tanggal Akhir',
    'create project': 'Buat Proyek',
    'edit project subtitle': 'Edit detail proyek',
    'delete project': 'Hapus Proyek',
    'save changes': 'Simpan Perubahan',
    'project information': 'Informasi Proyek',
    'owner': 'Pemilik',
    'created': 'Dibuat',
    'team members': 'Anggota Tim',
    'founder': 'Pendiri',
    'project owner': 'Pemilik Proyek',
    'add member project': 'Tambah Anggota',
    'create task': 'Buat Tugas',
    'create new task': 'Buat Tugas Baru',
    'create new task subtitle': 'Buat tugas baru untuk proyek Anda',
    'task title': 'Judul Tugas',
    'enter task title': 'Masukkan judul tugas',
    'task description': 'Deskripsi Tugas',
    'describe this task': 'Jelaskan tugas ini',
    'select project': 'Pilih Proyek',
    'task priority': 'Prioritas Tugas',
    'assign to': 'Tetapkan Kepada',
    'select team members': 'Pilih Anggota Tim',
    'select project first': 'Pilih Proyek Terlebih Dahulu',
    'edit task title': 'Edit Tugas',
    'edit task subtitle': 'Edit detail tugas',
    'project cannot be changed': 'Proyek tidak dapat diubah',
    'select all': 'Pilih Semua',
    'delete task': 'Hapus Tugas',
    'add team members': 'Tambah Anggota Tim',
    'add new members to': 'Tambah Anggota Baru ke',
    'current team members': 'Anggota Tim Saat Ini',
    'select users to add': 'Pilih Pengguna untuk Ditambah',
    'search username': 'Cari Username',
    'cancel action': 'Batal',
    'add selected members': 'Tambah Anggota Terpilih',
    'selected users': 'Pengguna Dipilih',
    'remove user': 'Hapus',
    'edit member role': 'Edit Peran Anggota',

    // Settings
    'settings subtitle': 'Manage your account settings',
    'profile information': 'Profile Information',
    'profile photo': 'Profile Photo',
    'full name': 'Full Name',
    email: 'Email',
    'email cannot be changed': 'Email cannot be changed',
    'edit profile': 'Edit Profile',
    saving: 'Saving...',
    'account info': 'Account Info',
    'member since': 'Member since:',
    active: 'Active',
    'quick actions': 'Quick Actions',
    'danger zone': 'Danger Zone',
    'delete account desc': 'Once you delete your account, there is no going back. Please be certain.',
    'choose file': 'Choose File',
    'no file chosen': 'No file chosen',
    'formats hint': 'Formats: JPG, PNG, GIF up to 512KB',
    upload: 'Upload',
    uploading: 'Uploading...',
    'choose theme': 'Choose Theme',
    'green theme': 'Green Theme',
    'default green theme': 'Default green theme',
    'blue theme': 'Blue Theme',
    'professional blue theme': 'Professional blue theme',
    'purple theme': 'Purple Theme',
    'elegant purple theme': 'Elegant purple theme',
    'choose language': 'Choose Language',
    indonesian: 'Indonesian',
    english: 'English',
    'demo user': 'Demo User',
    'demo email': 'demo@example.com',
    'name username required': 'Name and username are required',
    'username length requirement': 'Username must be 4-16 characters',
    'profile updated successfully': 'Profile updated successfully',
    'error saving profile': 'Error saving profile',
    'cannot load profile': 'Cannot load profile',
    'failed load profile': 'Failed to load profile',
    'error loading profile': 'Error loading profile',
    'profile photo updated successfully': 'Profile photo updated successfully',
    'failed upload profile photo': 'Failed to upload profile photo',
    'error uploading photo': 'Error uploading photo',
    'file size too large': 'File size too large',
    'file must be image': 'File must be an image',
    'remove image preview': 'Remove image preview',
    'change theme': 'Change Theme',
    'change language': 'Change Language',
    'delete account': 'Delete Account',
    'theme changed successfully': 'Theme changed successfully',
    'language changed successfully': 'Language changed successfully',
    delete_warning_1: 'Warning 1: Deleting your account will permanently remove all your data.',
    delete_warning_2: 'Warning 2: This action cannot be undone.',
    delete_warning_3: 'Warning 3: Are you sure you want to delete your account?',
    continue: 'Continue',
    'confirm delete': 'Yes, Delete My Account',
    'failed delete account': 'Failed to delete account',
    'error deleting account': 'Error deleting account',
    'processing': 'Processing...',
    'suspend': 'Suspend',
    'unsuspend': 'Remove Suspend',
    'ban': 'Ban',
    'unban': 'Unban',
    'confirmation': 'Confirmation',
    'suspend confirmation': 'Suspend Confirmation',
    'unban confirmation': 'Remove Ban',
    'suspend duration': 'Suspend Duration',
    'reason optional': 'Reason (optional)',
    'write reason': 'Write reason...',
    'no login methods': 'No login methods configured. Contact admin to enable login providers.',
    'no account': 'Don\'t have an account?',
    'sign up here': 'Sign up here',
    'admin panel': 'Admin Panel TaskApp',
    'sign in to admin': 'Sign in to Admin Panel',
    'sign in': 'Sign In',
    'sign up': 'Sign Up',
    'start free': 'Start Free',
    'view demo': 'View Demo',
    'start now free': 'Start Now - Free!',
    'only_founder_admin_can_edit': 'Only founder and admin can edit this field',
    'only_founder_can_edit_dates': 'Only founder can edit dates',
    'project_completed_tasks_cannot_edit': 'Completed project tasks cannot be edited',
    only_founder_admin_edit_title: 'Only founder admin edit title',
    only_founder_admin_edit_desc: 'Only founder admin edit desc',
    member_can_edit_status: 'Member can edit status',
    only_founder_admin_edit_priority: 'Only founder admin edit priority',
    only_founder_admin_edit_due_date: 'Only founder admin edit due date',
    assigned_to: 'Assigned To',
    create_project: 'Create Project',
    no_projects_yet: 'No projects yet',
    start_by_creating_first_project: 'Start by creating first project',

    // Special cases
    lang: 'en'
  },
  id: {
    // Navigation
    dashboard: 'Dasbor',
    projects: 'Proyek',
    team: 'Tim',
    analytics: 'Analitik',
    settings: 'Pengaturan',
    logout: 'Keluar',
    welcome: 'Selamat Datang',
    'dashboard subtitle': 'Selamat datang di dasbor Anda',
    'analytics dashboard': 'Dasbor Analitik',
    'analytics dashboard subtitle': 'Lihat wawasan dan metrik kinerja',
    'monthly comparison': 'Perbandingan Bulanan',
    'analytics loading': 'Memuat analitik...',
    'analytics load error': 'Gagal memuat analitik',
    'analytics error': 'Terjadi kesalahan saat memuat analitik',
    'analytics no data': 'Data analitik tidak tersedia',
    'comparison chart title': 'Perbandingan Bulanan',
    'this month': 'Bulan Ini',
    'last month': 'Bulan Lalu',
    'user reports': 'Laporan Pengguna',
    'user reports subtitle': 'Subjudul Laporan Pengguna',
    'generate monthly report': 'Hasilkan Laporan Bulanan',
    'month': 'Bulan',
    'year': 'Tahun',
    'download pdf report': 'Unduh Laporan PDF',
    'my projects': 'Proyek Saya',
    'my tasks': 'Tugas Saya',
    'teams joined': 'Tim Bergabung',
    'active teams': 'Tim Aktif',
    'contribution score': 'Skor Kontribusi',
    'generating': 'Menghasilkan...',
    'admin analytics title': 'Judul Analitik Admin',
    'admin analytics subtitle': 'Subjudul Analitik Admin',
    'real time label': 'Label Real Time',
    'total users': 'Total Pengguna',
    'active users': 'Pengguna Aktif',
    'completed projects': 'Proyek Selesai',
    'across all projects': 'Di Semua Proyek',
    'total admins': 'Total Admin',
    'system admins': 'Admin Sistem',
    'user registration trend': 'Tren Pendaftaran Pengguna',
    'user registration trend desc': 'Deskripsi Tren Pendaftaran Pengguna',
    'project status distribution title': 'Judul Distribusi Status Proyek',
    'project status distribution desc': 'Deskripsi Distribusi Status Proyek',
    'user activity overview': 'Ringkasan Aktivitas Pengguna',
    'active users vs new registrations over time': 'Pengguna Aktif vs Pendaftaran Baru Seiring Waktu',
    'yearly registration growth': 'Pertumbuhan Pendaftaran Tahunan',
    'yearly registration growth desc': 'Deskripsi Pertumbuhan Pendaftaran Tahunan',
    'last year': 'Tahun Lalu',
    'completed tasks': 'Tugas Selesai',
    'completion rate title': 'Tingkat Penyelesaian Tugas',
    'trend chart title': 'Tren Bulanan',
    'team growth title': 'Pertumbuhan Tim',

    // Team
    team_subtitle: 'Kelola anggota tim Anda',
    add_member: 'Tambah Anggota',
    team_search_placeholder: 'Cari anggota tim...',
    refresh: 'Perbarui',
    detail: 'Detail',
    team_empty: 'Tidak ada anggota tim ditemukan',

    // Common
    back: 'Kembali',
    cancel: 'Batal',
    createTask: 'Buat Tugas',
    edit: 'Edit',
    delete: 'Hapus',
    remove: 'Hapus',
    save: 'Simpan',
    loading: 'Memuat...',
    error: 'Kesalahan',
    success: 'Berhasil',
    'total projects': 'Total Proyek',
    'total tasks': 'Total Tugas',
    'total members': 'Total Anggota',
    'avg progress': 'Rata-rata Kemajuan',
    'undo': 'Undo',
    'redo': 'Redo',

    // Quick Actions
    qaNewProject: 'Mulai Proyek Baru',
    qaAddTask: 'Tambah Tugas Baru',
    qaInviteMember: 'Undang Anggota',

    // Task related
    tasks: 'Tugas',
    taskTitle: 'Judul Tugas',
    taskDescription: 'Deskripsi Tugas',
    taskPriority: 'Prioritas',
    status: 'Status',
    pending: 'Belum Dimulai',
    in_progress: 'Sedang Berjalan',
    review: 'Review',
    completed: 'Selesai',
    low: 'Rendah',
    medium: 'Sedang',
    high: 'Tinggi',
    urgent: 'Mendesak',
    endDate: 'Tanggal Deadline',
    assignTo: 'Tetapkan Kepada',
    selectAll: 'Pilih Semua',
    deselectAll: 'Batal Pilih Semua',
    membersSelected: 'Anggota Dipilih',
    selectProjectFirst: 'Pilih Proyek Terlebih Dahulu',
    createNewTask: 'Buat Tugas Baru',
    createNewTaskSubtitle: 'Tambahkan Tugas Baru Ke Proyek Anda',
    enterTaskTitle: 'Masukkan Judul Tugas',
    describeThisTask: 'Jelaskan Tugas Ini',
    selectProject: 'Pilih Proyek',
    description: 'Deskripsi',
    task_status_changed: 'Status tugas berubah',
    task_updated_successfully: 'Tugas berhasil diperbarui',
    task_deleted_successfully: 'Tugas berhasil dihapus',
    no_tasks_yet: 'Belum ada tugas',
    start_by_creating_first_task: 'Mulai dengan membuat tugas pertama',

    // Team related
    addTeamMemberTitle: 'Tambah Anggota Tim',
    addTeamMemberSubtitle: 'Tambahkan Anggota Baru Ke Tim Anda',
    searchUserLabel: 'Cari Pengguna',
    'enter username or email placeholder': 'Masukkan Username atau Email',
    searchButton: 'Cari',
    searchingStatus: 'Mencari...',
    selectTeamProject: 'Pilih Proyek Tim',
    chooseTeamProject: 'Pilih Proyek Tim',
    roleLabel: 'Peran',
    memberRole: 'Anggota',
    adminRole: 'Admin',
    founderRole: 'Pendiri',
    addTeamMemberButton: 'Tambah Anggota Tim',
    'add task': 'Tambah Tugas',
    'project history': 'Riwayat Proyek',
    'no changes yet': 'Belum Ada Perubahan',
    completeDataWarning: 'Peringatan Data Lengkap',
    pleaseCompleteAllFieldsMessage: 'Harap Lengkapi Semua Field Yang Diperlukan',
    successStatus: 'Berhasil',
    memberAddedSuccessfullyMessage: 'Anggota Berhasil Ditambahkan',
    'member removed successfully': 'Anggota Berhasil Dihapus',
    failedStatus: 'Gagal',
    failedAddMemberError: 'Gagal Menambah Anggota',
    errorOccurredMessage: 'Terjadi Kesalahan',
    selectUserLabel: 'Pilih Pengguna',
    memberDetails: 'Detail Anggota',
    editRole: 'Edit Peran',
    online: 'Online',
    monthlyData: 'Bergabung',
    lastActive: 'Terakhir Aktif',
    projectMemberships: 'Keanggotaan Proyek',
    thisMemberNotInAnyProject: 'Anggota Ini Tidak Ada Di Proyek Manapun',
    viewProject: 'Lihat Proyek',
    memberNotFound: 'Anggota Tidak Ditemukan',
    memberNotFoundDesc: 'Anggota Yang Diminta Tidak Dapat Ditemukan',
    noName: 'Tidak Ada Nama',
    member: 'Anggota',
    'confirm remove member': 'Konfirmasi Hapus Anggota ?',
    'are you sure remove member': 'Apakah Anda yakin menghapus anggota ?',
    'this action cannot be undone': 'tindakan ini tidak dapat dibatalkan ?',
    'confirm delete task': 'Konfirmasi Hapus Tugas ?',
    'are you sure delete task': 'Apakah Anda yakin menghapus tugas',
    'edit role for': 'Edit Peran untuk',
    'select new role': 'Pilih Peran Baru',
    'update role': 'Perbarui Peran',
    project_created_successfully: 'Proyek berhasil dibuat',
    member_details: 'Detail Anggota',
    project_memberships: 'Keanggotaan Proyek',
    monthly_data: 'data bulanan',
    view_project: 'Lihat Proyek',
    last_active: 'terakhir aktif',
    edit_member_role: 'Edit Peran Anggota',
    edit_member_role_subtitle: 'Edit subjudul peran anggota',
    member_information: 'Informasi Anggota',
    roles_in_projects: 'Peran Dalam Proyek',

    // Project related
    planning: 'Perencanaan',
    on_hold: 'Ditunda',
    'latest projects': 'Proyek Terbaru',
    'view all': 'Lihat Semua',
    'projects subtitle': 'Kelola semua proyek Anda',
    'new project': 'Proyek Baru',
    'members label': 'anggota',
    'tasks label': 'Tugas',
    'view details': 'Lihat Detail',
    'edit project': 'Edit Proyek',
    'create new project': 'Buat Proyek Baru',
    'create new project subtitle': 'Buat proyek baru untuk memulai',
    'project name': 'Nama Proyek',
    'enter project name': 'Masukkan nama proyek',
    'describe this project': 'Jelaskan proyek ini',
    'you can edit later': 'Anda dapat mengedit ini nanti',
    'project status': 'Status Proyek',
    'end date': 'Tanggal Akhir',
    'create project': 'Buat Proyek',
    'edit project subtitle': 'Edit detail proyek',
    'delete project': 'Delete Project',
    'cannot_delete_project_with_active_tasks': 'Cannot delete project with active tasks',
    'cannot_delete_project_with_pending_tasks': 'Cannot delete project with pending tasks',
    'cannot_delete_project_with_incomplete_tasks': 'Cannot delete project with incomplete tasks',
    'save changes': 'Save Changes',
    'project information': 'Informasi Proyek',
    'owner': 'Pemilik',
    'created': 'Dibuat',
    'team members': 'Anggota Tim',
    'founder': 'Pendiri',
    'project owner': 'Pemilik Proyek',
    'add member project': 'Tambah Anggota',
    'create task': 'Buat Tugas',
    'create new task': 'Buat Tugas Baru',
    'create new task subtitle': 'Buat tugas baru untuk proyek Anda',
    'task title': 'Judul Tugas',
    'enter task title': 'Masukkan judul tugas',
    'task description': 'Deskripsi Tugas',
    'describe this task': 'Jelaskan tugas ini',
    'select project': 'Pilih Proyek',
    'task priority': 'Prioritas Tugas',
    'assign to': 'Tetapkan Kepada',
    'select team members': 'Pilih Anggota Tim',
    'select project first': 'Pilih Proyek Terlebih Dahulu',
    'edit task title': 'Edit Tugas',
    'edit task subtitle': 'Edit detail tugas',
    'project cannot be changed': 'Proyek tidak dapat diubah',
    'select all': 'Pilih Semua',
    'delete task': 'Hapus Tugas',
    'add team members': 'Tambah Anggota Tim',
    'add new members to': 'Tambah Anggota Baru ke',
    'current team members': 'Anggota Tim Saat Ini',
    'select users to add': 'Pilih Pengguna untuk Ditambah',
    'search username': 'Cari Username',
    'cancel action': 'Batal',
    'add selected members': 'Tambah Anggota Terpilih',
    'selected users': 'Pengguna Dipilih',
    'remove user': 'Hapus',
    'edit member role': 'Edit Peran Anggota',

    // Settings
    'settings subtitle': 'Kelola pengaturan akun Anda',
    'profile information': 'Informasi Profil',
    'profile photo': 'Foto Profil',
    'full name': 'Nama Lengkap',
    email: 'Email',
    'email cannot be changed': 'Email tidak dapat diubah',
    'edit profile': 'Edit Profil',
    saving: 'Menyimpan...',
    'account info': 'Info Akun',
    'member since': 'Anggota sejak:',
    active: 'Aktif',
    'quick actions': 'Aksi Cepat',
    'danger zone': 'Zona Bahaya',
    'delete account desc': 'Setelah Anda menghapus akun, tidak ada jalan kembali. Pastikan Anda yakin.',
    'choose file': 'Pilih File',
    'no file chosen': 'Tidak ada file dipilih',
    'formats hint': 'Format: JPG, PNG, GIF hingga 512KB',
    upload: 'Unggah',
    uploading: 'Mengunggah...',
    'choose theme': 'Pilih Tema',
    'green theme': 'Tema Hijau',
    'default green theme': 'Tema hijau default',
    'blue theme': 'Tema Biru',
    'professional blue theme': 'Tema biru profesional',
    'purple theme': 'Tema Ungu',
    'elegant purple theme': 'Tema ungu elegan',
    'choose language': 'Pilih Bahasa',
    indonesian: 'Bahasa Indonesia',
    english: 'Bahasa Inggris',
    'demo user': 'Pengguna Demo',
    'demo email': 'demo@contoh.com',
    'name username required': 'Nama dan username diperlukan',
    'username length requirement': 'Username harus 4-16 karakter',
    'profile updated successfully': 'Profil berhasil diperbarui',
    'error saving profile': 'Kesalahan menyimpan profil',
    'cannot load profile': 'Tidak dapat memuat profil',
    'failed load profile': 'Gagal memuat profil',
    'error loading profile': 'Kesalahan memuat profil',
    'profile photo updated successfully': 'Foto profil berhasil diperbarui',
    'failed upload profile photo': 'Gagal mengunggah foto profil',
    'error uploading photo': 'Kesalahan mengunggah foto',
    'file size too large': 'Ukuran file terlalu besar',
    'file must be image': 'File harus berupa gambar',
    'remove image preview': 'Hapus pratinjau gambar',
    'change theme': 'Ubah Tema',
    'change language': 'Ubah Bahasa',
    'delete account': 'Hapus Akun',
    'theme changed successfully': 'Tema berhasil diubah',
    'language changed successfully': 'Bahasa berhasil diubah',
    delete_warning_1: 'Peringatan 1: Menghapus akun Anda akan secara permanen menghapus semua data Anda.',
    delete_warning_2: 'Peringatan 2: Tindakan ini tidak dapat dibatalkan.',
    delete_warning_3: 'Peringatan 3: Apakah Anda yakin ingin menghapus akun Anda?',
    continue: 'Lanjutkan',
    'confirm delete': 'Ya, Hapus Akun Saya',
    'failed delete account': 'Gagal menghapus akun',
    'error deleting account': 'Kesalahan menghapus akun',
    'processing': 'Memproses...',
    'suspend': 'Suspend',
    'unsuspend': 'Hapus Suspend',
    'ban': 'Ban',
    'unban': 'Unban',
    'confirmation': 'Konfirmasi',
    'suspend confirmation': 'Konfirmasi Suspend',
    'unban confirmation': 'Hapus Ban',
    'suspend duration': 'Durasi Suspend',
    'reason optional': 'Alasan (opsional)',
    'write reason': 'Tuliskan alasan...',
    'no login methods': 'Tidak ada metode login yang dikonfigurasi. Hubungi admin untuk mengaktifkan penyedia masuk.',
    'no account': 'Belum punya akun?',
    'sign up here': 'Daftar di sini',
    'admin panel': 'Panel Admin TaskApp',
    'sign in to admin': 'Masuk ke Admin Panel',
    'sign in': 'Masuk',
    'sign up': 'Daftar',
    'start free': 'Mulai Gratis',
    'view demo': 'Lihat Demo',
    'start now free': 'Mulai Sekarang - Gratis!',
    theme_changed_successfully: 'Tema Berhasil Diubah',
    language_changed_successfully: 'Bahasa Berhasil Diubah',
    'only_founder_admin_can_edit': 'Hanya pendiri dan admin yang dapat mengedit field ini',
    'only_founder_can_edit_dates': 'Hanya pendiri yang dapat mengedit tanggal',
    'project_completed_tasks_cannot_edit': 'Tugas proyek yang sudah selesai tidak dapat diedit',
    'cannot_delete_project_not_completed': 'Tidak dapat menghapus proyek yang belum selesai',
    create_project: 'Buat Proyek',
    no_projects_yet: 'Belum ada proyek',
    start_by_creating_first_project: 'Mulai dengan membuat proyek pertama',

    // Special cases
    lang: 'id'
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState('en')

  // Load language from localStorage or default to 'en'
  useEffect(() => {
    const savedLang = localStorage.getItem('language')
    console.log('Saved language from localStorage:', savedLang)
    if (savedLang && (savedLang === 'en' || savedLang === 'id')) {
      console.log('Setting language to saved value:', savedLang)
      setLang(savedLang)
    } else {
      console.log('Setting language to default: en')
      setLang('en') // default to English
    }
  }, [])

  // Save language to localStorage when it changes
  useEffect(() => {
    console.log('Saving language to localStorage:', lang)
    localStorage.setItem('language', lang)
  }, [lang])

  const t = (key: string) => {
    const currentTranslations = translations[lang as keyof typeof translations] || translations.en
    console.log(`Translating key "${key}" in language "${lang}":`, currentTranslations[key as keyof typeof currentTranslations])
    return currentTranslations[key as keyof typeof currentTranslations] || key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
